export const elements = {

    txtEmail: '[data-testid="email"]',
    btnLogin: '[data-testid="btnLogin"]',
    btnProfile: '[href="/Tab/Account"]',
    btnOrder: '[href="/Tab/Order"]',
    btnsignUp: '[data-testid="signUp"]',
    txtFirstName: '[data-testid="firstName"]',
    txtLastName: '[data-testid="lastName"]',
    txtPhoneNumber: '[data-testid="phone"]',
    txtEmailCreation: "[placeholder='Email Address']",
    txtPassword: '[data-testid="password"]',
    txtConfirmPassword: '[data-testid="repassword"]',
    btnCreate: '[data-testid="create"]',
    username: '[data-testid="CustomerName"]',
    product: '[data-testid="productDetails"]',
    btnContinueToCheckout: '[data-testid="selectAddressOrContinueToPayment"]',
    btnCheckout: '[data-testid="completeCheckout"]',
    btnPurchase: '[data-testid="addToCart"]',
    item: '[data-testid="item-0"]',
    processingOrders: '[data-testid="Placed"]',
    btnCancelOrder: '[data-testid="item-0"] > :nth-child(3) > [data-testid="cancel"]',
    btnConfirmCancelOrder: '[data-testid="confirm"]',
    btnRemove: '[data-testid="remove"]',
    msgCartEmpty: '[data-testid="emptyCart"]',
    alertMsg: '[data-testid="warning"]'
}